name: Deploy Infrastructure

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'infrastructure/**'
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev, staging, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Terraform Configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infrastructure

      - name: Terraform Plan (Dev)
        run: terraform plan -var-file="environments/dev.tfvars" -no-color
        working-directory: ./infrastructure

  deploy-dev:
    if: github.ref == 'refs/heads/develop' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    needs: validate
    runs-on: ubuntu-latest
    name: Deploy to Development
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create \
            --name sayzhong-dev-rg \
            --location "East US" \
            --tags Environment=dev Application=sayzhong

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure

      - name: Terraform Plan
        run: terraform plan -var-file="environments/dev.tfvars" -out="tfplan-dev"
        working-directory: ./infrastructure

      - name: Terraform Apply
        run: terraform apply tfplan-dev
        working-directory: ./infrastructure

      - name: Terraform Output
        run: terraform output -json > ../deployment-outputs-dev.json
        working-directory: ./infrastructure

  deploy-staging:
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    needs: validate
    runs-on: ubuntu-latest
    name: Deploy to Staging
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create \
            --name sayzhong-staging-rg \
            --location "East US 2" \
            --tags Environment=staging Application=sayzhong

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure

      - name: Terraform Plan
        run: terraform plan -var-file="environments/staging.tfvars" -out="tfplan-staging"
        working-directory: ./infrastructure

      - name: Terraform Apply
        run: terraform apply tfplan-staging
        working-directory: ./infrastructure

      - name: Terraform Output
        run: terraform output -json > ../deployment-outputs-staging.json
        working-directory: ./infrastructure

  deploy-prod:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    needs: validate
    runs-on: ubuntu-latest
    name: Deploy to Production
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create \
            --name sayzhong-prod-rg \
            --location "East US" \
            --tags Environment=prod Application=sayzhong

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure

      - name: Terraform Plan
        run: terraform plan -var-file="environments/prod.tfvars" -out="tfplan-prod"
        working-directory: ./infrastructure

      - name: Terraform Apply
        run: terraform apply tfplan-prod
        working-directory: ./infrastructure

      - name: Terraform Output
        run: terraform output -json > ../deployment-outputs-prod.json
        working-directory: ./infrastructure

      - name: Output Deployment Information
        run: |
          echo "Production deployment completed successfully!"
          echo "Check the Azure portal for deployment details."
